-- KR-021: complete metadata-only audit coverage for patient and appointment events.

alter table public.audit_events drop constraint if exists audit_events_type_check;

alter table public.audit_events
  add constraint audit_events_type_check
  check (event_type in (
    'clinic.created', 'clinic.profile_updated', 'auth.signup', 'auth.login',
    'auth.mfa_enrolled', 'auth.session_revoked', 'auth.idle_lock',
    'auth.outbox_discarded', 'auth.password_changed', 'member.invited',
    'member.removed', 'access.denied', 'service.created', 'service.updated',
    'service.deleted', 'booking.accepted', 'booking.declined',
    'patient.created', 'patient.updated', 'appointment.set', 'chart.appended',
    'quote.created', 'payment.recorded', 'opening_balance.noted',
    'collections.viewed', 'import.started', 'import.completed', 'import.failed',
    'import.checklist_updated', 'entitlement.trial_expired',
    'entitlement.grace_granted', 'entitlement.expired',
    'entitlement.past_due', 'entitlement.restored',
    'billing.checkout_started', 'billing.payment_succeeded',
    'billing.payment_failed', 'export.started', 'export.completed',
    'export.failed'
  ));

create or replace function private.audit_patient_appointment_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_metadata jsonb := '{}'::jsonb;
begin
  if new.event_type not in (
    'patient.created',
    'patient.updated',
    'appointment.set'
  ) then
    return new;
  end if;

  if new.record_id is null then
    raise exception 'audited clinic event requires record_id' using errcode = '22023';
  end if;

  if new.event_type = 'appointment.set' then
    if jsonb_typeof(new.payload -> 'patientId') <> 'string'
       or (new.payload ->> 'patientId')::uuid is null
       or (
         new.payload ? 'status'
         and new.payload ->> 'status' not in (
           'confirmed',
           'pending_review',
           'waiting',
           'in_chair',
           'complete',
           'cancelled',
           'no_show',
           'booked'
         )
       ) then
      raise exception 'invalid appointment audit metadata' using errcode = '22023';
    end if;

    v_metadata := jsonb_strip_nulls(jsonb_build_object(
      'patient_id', new.payload ->> 'patientId',
      'status', new.payload ->> 'status'
    ));
  end if;

  insert into public.audit_events (
    tenant_id,
    actor_user_id,
    event_type,
    record_id,
    metadata
  ) values (
    new.tenant_id,
    new.actor_user_id,
    new.event_type,
    new.record_id,
    v_metadata
  );

  return new;
end;
$$;

revoke all on function private.audit_patient_appointment_event() from public;

drop trigger if exists clinic_events_audit_patient_appointment
  on public.clinic_events;
create trigger clinic_events_audit_patient_appointment
after insert on public.clinic_events
for each row execute function private.audit_patient_appointment_event();

create or replace function private.reject_forged_extended_audit_event()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if current_user = 'authenticated'
     and new.event_type in (
       'patient.created',
       'patient.updated',
       'appointment.set',
       'chart.appended',
       'quote.created',
       'payment.recorded',
       'opening_balance.noted',
       'import.started',
       'import.completed',
       'import.failed',
       'import.checklist_updated'
     ) then
    raise exception 'extended audit events are generated by committed actions'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

revoke all on function private.reject_forged_extended_audit_event() from public;

drop trigger if exists audit_events_reject_forged_extended
  on public.audit_events;
create trigger audit_events_reject_forged_extended
before insert on public.audit_events
for each row execute function private.reject_forged_extended_audit_event();

notify pgrst, 'reload schema';
